language: node_js
sudo: false

node_js:
  # Use the explicit NodeJS LTS version (https://github.com/nodejs/Release#release-schedule) to avoid any
  # automatic upgrade of the version. This ensures that all Travis jobs run consistently and don't have
  # different Node versions.
  - '8.12.0'

branches:
  only:
  - master

addons:
  chrome: stable
  firefox: latest

env:
  matrix:
    - MODE=lint
    # TODO(josephperrott): Add e2e tests
    # - MODE=e2e
    - MODE=test

install:
  - npm install

script:
  - ./scripts/ci/build-and-test.sh

cache:
  directories:
    - node_modules
