language: node_js
sudo: false

node_js:
  - '6.9.1'

branches:
  only:
  - master

env:
  global:
  - LOGS_DIR=/tmp/material-angular-io-build/logs
  - SAUCE_USERNAME=angular-ci
  - SAUCE_ACCESS_KEY=9b988f434ff8-fbca-8aa4-4ae3-35442987
  - BROWSER_STACK_USERNAME=angularteam1
  - BROWSER_STACK_ACCESS_KEY=BWCd4SynLzdDcv8xtzsB
  - BROWSER_PROVIDER_READY_FILE=/tmp/material-angular-io-build/readyfile
  - BROWSER_PROVIDER_ERROR_FILE=/tmp/material-angular-io-build/errorfile
  matrix:
    - MODE=lint
    # TODO(josephperrott): Add e2e tests
    # - MODE=e2e
    - MODE=saucelabs
    - MODE=browserstack

matrix:
  fast_finish: true

install:
  - npm install

before_script:
  - mkdir -p $LOGS_DIR

script:
  - ./scripts/ci/build-and-test.sh

cache:
  directories:
    - node_modules